### ISSUE TITLE
Crash after install, full remove and tryed fix repair (framework 2-3.5.-4.6-4.8) 

### ISSUE THREAD

**Issue by Grim-Lord** [mikeyhalla/MenuTools#2] opened 2020-07-30 23:06 UTC
Please Help Always get This Error on Win7 x64 Ultimate

![Menu Tools Error](https://user-images.githubusercontent.com/69019150/88982851-45376200-d2c1-11ea-9e07-b12c5a5df0c3.JPG)

**Comment by xCONFLiCTiONx** [comment] 2020-07-31 00:22
The program only supports English. I'm really sorry man. I'm not sure if i'll ever add support for other languages. You can try enabling English in Windows Settings and that would likely fix it.

**Comment by xCONFLiCTiONx** [comment] 2020-07-31 21:08
I'll be closing this issue unless you have anything else.

**Comment by Grim-Lord** [comment] 2020-08-02 00:23
Thanks for a quick response,The MenuTools are great to access those so needed shortcuts.

About the error is not the language i have this tool installed in another pc is a laptop not a desktop like this one and works fine in my language same o.s.

In this PC first i used win 8 9200 x64 pro in English but was incompatible, reinstalled the older win 7 ultimate x64 with all languages and crashes in booth  gives this error on event viewer (Address module with fault: C:\Windows\assembly\NativeImages_v4.0.30319_64\System\cd4fe4e1ff2a1ebe13c9a9f33689df21\System.ni.dll)

![Error In english 1 2](https://user-images.githubusercontent.com/69019150/89112679-3508b980-d45e-11ea-92e0-95881df83f49.JPG)
![Error In english 1 1](https://user-images.githubusercontent.com/69019150/89112680-35a15000-d45e-11ea-9d78-9017ba0792cd.JPG)

what can i do i just love to use this tool do have to forget about it (-_-) help

**Comment by xCONFLiCTiONx** [comment] 2020-08-02 02:49
I'll look into it further sometime this week. My apologies for the inconvenience.

**Comment by xCONFLiCTiONx** [comment] 2020-08-03 15:24
It appears that there was an update for the [SharpShell ](https://github.com/dwmkerr/sharpshell) extension a while back that didn't get added to MenuTools. I just added it in the attached file. Please let me know if this works so I can add it to the release.

If it doesn't please paste text only so I can copy and paste it into a translator. I only speak English and need exact details. A lot is obvious but I need exacts here.

[Setup_MenuTools.zip](https://github.com/xCONFLiCTiONx/MenuTools/files/5016836/Setup_MenuTools.zip)

**Comment by Grim-Lord** [comment] 2020-08-04 03:21
Thanks for the help and sorry for the inconvenience, here i put the error properly translated, after tried the new setup, i get this error and explorer is forced to restart then in event viewer - Applications the error appears :

Faulting application name: explorer.exe, version: 6.1.7601.23537, timestamp: 0x57c44efe
Faulty module name: System.ni.dll, version: 4.8.4001.0, timestamp: 0x5d37b3ae
Exception code: 0x00000000
Fault deviation: 0x000000000092b684
Failed process ID: 0x102c
Failed application start date / time: 0x01d66a09cddeb733
Faulting application path: C: \ Windows \ explorer.exe
Faulting module path: C: \ Windows \ assembly \ NativeImages_v4.0.30319_64 \ System \ cd4fe4e1ff2a1ebe13c9a9f33689df21 \ System.ni.dll
Report ID: 161f01c1-d5fe-11ea-9659-001e8c8ac998

I going to try in English, but that should not be the problem, because it works fine, from the the first try on my laptop that is in my language, maybe my CPU is not compatible ?

I using CPU Type Dual Core Intel Core 2 Duo E4500, if i saying something stupid sorry for my ignorance  in advance, was just a thought, if in English the application work´s fine i will say something if not i will wait, one more time thank you for your help.

**Comment by xCONFLiCTiONx** [comment] 2020-08-04 14:37
I'll wait until you report back on whether setting English has fixed the issue for you.
MenuTools is and has been working perfectly on my machine and I cannot reproduce your error.
If setting English doesn't fix it, please uninstall completely and go to where you installed and make sure to delete everything then try again after rebooting.

**Comment by xCONFLiCTiONx** [comment] 2020-08-05 15:02
I'll need a response soon else i'll assume that this was fixed by enabling English on your system and will close this issue. I do not see anything in MenuTools that should cause any issues other than it being only in English. It will not work on an OS that doesn't have the English pack installed.

Things to consider if enabling English doesn't resolve the issue:

- Run SFC and DISM and then do a disk check
- Run a virus/malware complete scan
- Do a full reinstall of Windows

As I stated, MenuTools runs perfectly on my machine and I do not see any issues at all. I want to help you resolve this but will need a reply or something.

Thank you!

**Comment by Grim-Lord** [comment] 2020-08-10 08:52
Sorry for the later response, this week i worked overtime, i was low on energy to check the forum.

In My Laptop windows 7 ultimate x64 (PT-PT) after upgraded framework to version 4.8 works just fine. Was no big deal, just worked.

On my HP desktop same O.S w7 full updates same apps don't run gives that error, then i tried windows 8 PRO 9200 English only same crash and error, so changed again to win 7 auto activate trough bios, updates again, but no luck with this small great app.

Change locale and language then reboot, first i always remove the application using IObit Uninstaller PRO reboot and then install. 

Thank for the effort in helping me, but it seems that this app don't like my desktop, i gonna keep using it on my laptop, with open shell, patched themes, and even so worked just fine on the first try. Thank you again.

**Comment by xCONFLiCTiONx** [comment] 2020-08-10 16:09
There are 2 zip files attached:
* [DEBUG.zip](https://github.com/xCONFLiCTiONx/MenuTools/files/5051979/DEBUG.zip) is the one that you need to use for the instructions below
* [MenuToolsSetup.zip](https://github.com/xCONFLiCTiONx/MenuTools/files/5051980/MenuToolsSetup.zip) is the install-able version if everything works in the DEBUG version.

## !!IMPORTANT STEPS!!

***You must follow this exactly:***

I went back through your first report and noticed in the screenshot you were running version 5.5 which is several releases behind. 

I changed the framework version to `4.0` just to rule that out.

What you need to do:
* Make sure you have English installed on Windows and set as the primary language
* Uninstall MenuTools if it's installed
* Go to `%programfiles(x86)%` and delete `MenuTools` if it exists
* Go to `%temp%` and delete everything in there
* Run regedit and go to `HKEY_LOCAL_MACHINE\SOFTWARE` and look for `MenuTools` and delete it if it exists.
* Reboot your pc (not shutdown)
* Once rebooted, extract `MenuTools` to your desktop and double click on `MenuTools.exe` and it will install



After you find if this worked or not, uninstall:
* To uninstall create a shortcut to `MenuTools.exe` and right click on the new shortcut and click on Properties then add `-u` or `-uninstall` to the end of the command:
`"%USERPROFILE%\Desktop\DEBUG\MenuTools.exe" -uninstall`
* Double click on the shortcut and let it uninstall (say ok and yes to all dialog's - if you don't run as admin, it will ask you twice if you want to uninstall)

I created an install-able version too if this does work. You'll have to uninstall the `DEBUG` version first before you install this one.

**Comment by Grim-Lord** [comment] 2020-08-11 11:40
I clicked the DEBUG modified and uninstalled then from desktop, run the setup and get this error, sorry the language don't change anything. Thank again you for your help.

Faulting application name: explorer.exe, version: 6.1.7601.23537, time stamp: 0x57c44efe
Faulting module name: System.ni.dll, version: 4.8.4001.0, time stamp: 0x5d37b3ae
Exception code: 0x00000000
Fault offset: 0x000000000092b684
Faulting process id: 0x684
Faulting application start time: 0x01d66fca23439a51
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_64\System\cd4fe4e1ff2a1ebe13c9a9f33689df21\System.ni.dll
Report Id: 31a66a09-dbbe-11ea-bc03-001e8c8ac998

![Error In english 1](https://user-images.githubusercontent.com/69019150/89893088-a1f32080-dbcf-11ea-82ae-7bc124fbdf17.JPG)

![Error In english 2](https://user-images.githubusercontent.com/69019150/89893105-aae3f200-dbcf-11ea-829e-843c7eb7cee9.JPG)

**Comment by xCONFLiCTiONx** [comment] 2020-08-11 13:40
I apologize for not looking more thoroughly. It appears that there is an issue checking the following keys in the registry.

Make sure the following keys exist:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced`
`Hidden`
`ShowSuperHidden`

Do those keys exist? Screenshot that for me and we should have our answer.

Here is another updated version with a more thorough message on catching the error though the above should tell us the issue: 
[MenuToolsSetup.zip](https://github.com/xCONFLiCTiONx/MenuTools/files/5057274/MenuToolsSetup.zip)

**Comment by xCONFLiCTiONx** [comment] 2020-08-14 11:38
I'll have to close this ticket soon so please reply soon with information from the above post.

**Comment by Grim-Lord** [comment] 2020-08-15 18:47
Updated version the same error, forced to abort explorer crash.

The keys yes exist they exist in English, the same values as in my laptop that it works.

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
Hidden                                         1
ShowSuperHidden                       0

![Hiden   1](https://user-images.githubusercontent.com/69019150/90319355-44dccf00-df2f-11ea-98cf-9b778b6eda32.JPG)
![Super Hiden   0](https://user-images.githubusercontent.com/69019150/90319358-460dfc00-df2f-11ea-8f66-718e97cd3b85.JPG)

Thank you for trying to fix this error, one day we will now why this app is crashing.

**Comment by xCONFLiCTiONx** [comment] 2020-08-17 18:09
If you got the same error then something is very much wrong and it's not MenuTools. The last version I gave you handles the same error differently so the error output would be completely different which is what I needed and the whole reason I wrote it so that it can give a bit more information.

If you press ignore, what is the error then? ALSO, while the error is showing, open task manager and right click on MenuTools and open file location. Is it opening where you installed the latest version?

Screenshot all the errors you receive using the newest version and pressing ignore for all of them, if it has any other errors:  [MenuToolsSetup.zip](https://github.com/xCONFLiCTiONx/MenuTools/files/5057274/MenuToolsSetup.zip)

I'll continue to try and resolve this so long as you continue to provide me with debug information as I've said before, it works on all my other computers and yours is the only one it doesn't so I need YOU to debug it for me and send me the output.

Thank you for being patient with me on this matter. It can be very difficult debugging when that computer isn't accessible.

EDIT:
It would be great if we could rule out your OS installation. Have you ran SFC and DISM at all since we've been trying to resolve this? When was the last time you installed Windows on that device? You could also do an in-place upgrade which would really make me feel a lot better knowing that it's not just your installation that's the issue.

My final advice is to run and in-place upgrade or completely reinstall Windows. I know how laughable that sounds but I can't find any reason why it shouldn't work.

**Closed as completed** 2020-08-23 13:26 UTC

**Comment by Grim-Lord** [comment] 2020-11-22 18:25
xCONFLiCTiONx xMenuTools v7.2.0.0 is working just fine, thank you for the new release, after setup gives error again , then i installed the following steps to fix it in win 7 ultimate x64 Pt-Pt

- Microsoft .NET Framework 4.7.1 (Offline Installer) for Windows 7 SP1
- Microsoft .NET Framework 4.7.2 (Offline Installer) for Windows 7 SP1
- NET Framework 4.8 (Offline Installer) for Windows 7 SP1

Trick used change original place to [ C:\Program Files\MenuTools ] insted of [ C:\Program Files (x86)\MenuTools ]

- Only then i see the light (The trick to fix the flickering and error) is go folder options and click show system files, restart explorer and then unpick back to hide system files, (i always have show hidden files so is on) .

Now is working thank you for the support and maybe this fix can help some one else with problems in win 7, i have seen the review of this app on InsaneForums was there i see the update v7.2 and tried again with success.

**Comment by xCONFLiCTiONx** [comment] 2020-11-22 18:35
I'm glad you got it working and thank you for reporting your success steps! I'll look into this and see if I can do something with this for future releases.

**Comment by xCONFLiCTiONx** [comment] 2020-11-26 19:02
I released 7.3 that defaults the installation path to C:\Program Files\xMenuTools. That is the only change in this release so up to you if you want to download and install it. Just make certain that you uninstall the old version first.

**Comment by Grim-Lord** [comment] 2021-02-04 10:09
The new version xCONFLiCTiONx xMenuTools v7.6.0.0 after uninstall the older xCONFLiCTiONx xMenuTools v7.2.0.0, this update  installed just fine, and now it works without any problem on booth laptop and desktop, thank for your support and this great tool for every day use.

**Comment by xCONFLiCTiONx** [comment] 2021-02-04 12:40
Thanks @Grim-Lord and I'm glad it's working!
